# General
name: Ivan Zlatev
url: http://ivanz.github.io

highlighter: pygments
safe: true 
lsi: false
pygments: true
markdown: redcarpet
redcarpet: 
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]


paginate: 5
permalink: /:year/:month/:day/:title/

# Social share and comments.
disqus-id: ivanz
twitter: ivanzlatev
github: ivanz
soundcloud: psyvian

# RSS feed
rss-feed-limit: 50
rss-show-full: "yes"