# Site settings

name: Ivan Zlatev
url: http://ivanz.com
baseurl: ""

author: 'Ivan Zlatev'
author_image: "/assets/images/author.jpg"

title: "Ivan's Brain Dump"
description: ""

email: ""

logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/blog-cover.jpg"


# System settings

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
gems: 
 - jekyll-paginate
 - jemoji

paginate: 5
permalink: /:year/:month/:day/:title/

# Social share and comments

disqus: ivanz

# Social icons and sharing options

twitter_handle: '@ivanzlatev'

social:
  - icon:	twitter
    url:	https://twitter.com/ivanzlatev
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/ivanz
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
    
  - icon:	linkedin
    url:	https://uk.linkedin.com/in/ivanzlatev
    desc:	Connect with me on LinkedIn
    share_url:
    share_title:
    share_link:

  - icon:	rss
    url:	http://ivanz.com/feed
    desc:	Subscribe to my RSS Feed
    share_url:
    share_title:
    share_link:

# RSS feed
rss-feed-limit: 50
rss-show-full: "yes"