# General
name: Ivan Zlatev
description: 
url: http://ivanz.github.io

highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: ivanz
twitter: ivanzlatev
github: ivanz
soundcloud: psyvian

# RSS feed
rss-feed-limit: 50
rss-show-full: "yes"