# General
name: Ivan Zlatev
url: http://127.0.0.1:4000/

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
gems: ['jekyll-paginate']
  
paginate: 5
permalink: /:year/:month/:day/:title/

# Social share and comments.
disqus-id: ivanz
twitter: ivanzlatev
github: ivanz
soundcloud: psyvian

# RSS feed
rss-feed-limit: 50
rss-show-full: "yes"